### PR TITLE
Refactored internal dictionary structure

### PR DESCRIPTION
**Pull request by softwx**
Refactored internal dictionary structure
Added staged dictionary building for improved speed
Optimized Lookup
Created new EditDistance class to allow future addition of alternate edit distance functions
Added method xml comments

### CODE REVIEW

**Comment by wolfgarbe** [comment]
Thank you Steve. I think there is a small problem in line 731:
```

                            case Verbosity.Top:
                                {
                                    maxEditDistance2 = distance;  //### if maxEditDistance2 is set to distance
                                    if (suggestions.Count != 0)
                                    {
                                        if (distance < maxEditDistance2  //### why we would check it here again?                                            || suggestionCount > suggestions[0].count)
                                        {
                                            suggestions[0] = si;
                                        }
                                        continue;
                                    }
                                    break;
                                }
```

**Comment by softwx** [comment]
You're right. I'll make a quick fix to that.

**Comment by softwx** [comment]
In doing some timing tests, it seems that removing the `DeleteInSuggestionPrefix` call speeds up the results, even though it increases the number of calls to the Damerau method. Also, testing shows that the `inputLen == 1` optimization I recently added doesn't really contribute anything, so I'm going to remove it.

**Comment by wolfgarbe** [comment]
>  I think the best thing would be to include a Verbosity test so that only gets called for Top and Closes, but not for All.

Yes, something like:

if((verbosity != Verbosity.All)  && !deleteInSuggestionPrefix(candidate, suggestion, prefixLength)) continue;
if (!hashset2.Add(suggestion)) continue;
distance = distanceComparer.Compare(suggestion, maxEditDistance2);

**Comment by wolfgarbe** [comment]
Thank you Steve, great job! Any specific reason why you changed the Intellisense description summary for the Verbosity Enum values back to plain comments? I thought it would be helpful for the user to have some explanation what the values mean directly in the IDE when using the library, without looking into the source code.

**Comment by softwx** [comment]
No, I like intellisense comments. That was unintentional.

**Comment by wolfgarbe** [comment]
Take your time, there's no hurry. Meanwhile I will work on the partitioning.

**Pull request merged**
