### PR TITLE
Target package to net framework as well

### PR DESCRIPTION
**Pull request by hanabi1224**
Target to .net framework as well to make life easier

### CODE REVIEW

**Comment by hanabi1224** [comment]
@wolfgarbe  This PR is to make nuget package target to .net framework as well, please let me know your concerns, thanks!

**Comment by wolfgarbe** [comment]
You want to change <TargetFramework>netstandard2.0</TargetFramework> to    <TargetFrameworks>netstandard2.0;net461;net47;</TargetFrameworks>
MSBuild will then compile the SymSpell library for each of those frameworks. It will produce many .dlls, one for each target framework.

Why do you want to do this? A single Net Standard library can be used from both Net Core and Net Framework projects: https://docs.microsoft.com/en-us/dotnet/standard/net-standard
So what is the benefit of creating different libraries for each platform?

**Comment by hanabi1224** [comment]
@wolfgarbe  In practice netstandard is not 100% compatible with .net framework projects, there're many edge cases to work around, that's why all popular .net libraries targets both netstandard and netframework

**Comment by wolfgarbe** [comment]
Thank you for the contribution!

**Comment by hanabi1224** [comment]
@wolfgarbe  Thank you for your great lib!  What's the  plan of next nuget publish?  I saw latest nuget package is 6.0.0 from 5 months ago

**Comment by wolfgarbe** [comment]
Yes, I should have done this already.

**Pull request merged**
